### ISSUE TITLE
abbreviate function rounded up when show `K`, `M` and `B`

### ISSUE THREAD

**Issue by Bundara123** [pqt/abbreviate#9]
I don't want to round up when showing the short number. ex:
![image](https://user-images.githubusercontent.com/13432086/108151281-f3ddab80-7108-11eb-85f8-57b3c8c37186.png)

https://runkit.com/embed/9p8z4kgxw3n2

**Comment by pqt** [comment]
Hey @Bundara123 I totally missed this issue!

I see in your posted link you adjusted the decimal places for display, is this what you wanted as the end result?

![](https://i.imgur.com/dkfoCWT.png)

**Comment by pqt** [comment]
Just doing a bit of clean up around my repos, if you still have some sort of concern about this please let me know by making a new issue!
